# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FT60bW3UBpEezon4f9l24k0IP6_B_Ysb
"""

# Function, variable and class
# Ham tra ve gia tri thoi gian tre han cua cong viec
def cal_time(val_a, val_b):
    if val_a - val_b > 0:
        return 0
    else:
        return val_b - val_a

# Dinh nghia mot cong viec - define a work
class work:
    # Khoi tao gia tri
    def __init__(self, name, time_work, time_end, weight):
        self.name_work = name # Ten cong viec
        self.time_work = time_work # Thoi gian thuc hien cong viec
        self.time_end = time_end # Thoi gian toi han
        self.weight = weight # Trong so

# Dinh nghia mot danh sach cac cong viec - define a list of work
class LPT:
    # Khoi tao gia tri
    def _init_List(self, val_a):
        self.volume = val_a
        self.list_work = []; # Tao danh sach rong
        for i in range(0, self.volume):
            print(f"--Công việc thứ {i+1}-- ")
            temp1 = input("Nhập tên công việc: " )
            temp2 = float(input("Nhập thời gian gia công của công việc: " ))
            temp3 = float(input("Nhập thời gian tới hạn của công việc: " ))
            temp4 = float(input("Nhập trọng số của công việc: "))
            self.list_work.append(work(temp1, temp2, temp3, temp4)); # Khoi tao gia tri cho phan tu vua them vao danh sach

        self.total_gia_cong_time = 0
        self.total_late_time = 0
        self.total_deadline_time = 0
        self.total_time_line = 0

        self.mean_done_time = 0
        self.mean_work = 0
        self.mean_late = 0

        self.do_huu_dung = 0

    # Tinh cac chi so va thu tu cong viec theo LPT
    def calculate(self):
        # Sắp xếp danh sách công việc theo quy tắc LPT
        self.list_work = sorted(self.list_work, key = lambda x: x.time_work, reverse = True)

        self.time_line = [self.list_work[0].time_work]

        for i in range(self.volume):
            # Tinh Tong thoi gian cong viec tai thoi diem cong viec thu i duoc thuc hien

            self.total_gia_cong_time += self.list_work[i].time_work
            # Tinh tong thoi gian du thua cho den thoi diem cong viec i

            self.total_late_time += cal_time(self.list_work[i].time_end, self.total_gia_cong_time)

            self.total_deadline_time += self.list_work[i].time_end

            if i > 0:
                self.time_line.append(self.time_line[i - 1] + self.list_work[i].time_work)

            self.total_time_line += self.time_line[i]

        self.process = [i.name_work for i in self.list_work]

        self.mean_done_time = self.total_time_line / self.volume

        self.do_huu_dung = round(self.total_gia_cong_time / self.total_time_line * 100, 2)

        self.mean_work = round(self.total_time_line / self.total_gia_cong_time, 3)

        self.mean_late = self.total_late_time / self.volume


    # Xuat ra command
    def show(self):
        print('-----------------------')
        print(f'Tổng thời gian gia công: {self.total_gia_cong_time}')
        print(f'Tổng thời gian trễ hạn: {self.total_late_time}')
        print(f'Process: {self.process}')
        print(f'Time line: {self.time_line}')
        print(f'Tổng thời gian time line: {self.total_time_line}')
        print(f'Tổng thời gian công việc: {self.total_time_line}')
        print(f'Tổng thời gian tới hạn: {self.total_deadline_time}')
        print(f'Thời gian hoàn thành trung bình: {self.mean_done_time}')
        print(f'Độ hữu dụng: {self.do_huu_dung}')
        print(f'Số lượng công việc trung bình: {self.mean_work}')
        print(f'Độ trễ trung bình: {self.mean_late}')

#import h_SPT as lpt

#list_work = lpt.LPT()
list_work = LPT()

list_work._init_List(int(input("Nhập số lượng công việc: ")))

list_work.calculate()

list_work.show()